#! /bin/bash

# ===========================================================

set -x

export TAPPERFROMGIT
export GITPREFIXTAPPERLIBS
export GITPREFIXTESTSUITES
export PYTHONSTATICTWEAKS

# ===========================================================

# Perl libs
/tmp/tapper-starterkit/utils/prepare-perlmodule \
 Test::TAPv13 \
 WWW::Mechanize \
 App::Bootstrap::Perl \
 Tapper::Remote \
 Tapper::PRC \
 Tapper::Installer \
 Tapper::TestSuite::AutoTest \
 Tapper::TestSuite::Benchmark::Perl::Formance \
 Tapper::TestSuite::Netperf \
 Tapper::TestSuite::HWTrack

# ==================== Python test suites ====================

PYTHONPREFIX=/opt/tapper/python

# Python test suites
if [ "x1" == "x$TAPPERFROMGIT" ] ; then
    cd /tmp
    if [ ! -d OSRC-TestSuites ] ; then git clone git://wotan/tapper/OSRC-TestSuites ; fi
    if [ -d OSRC-TestSuites ] ; then
        cd OSRC-TestSuites
        git pull
        TESTSUITES=$(cat python/CLIENTPKG)
        /tmp/tapper-starterkit/utils/prepare-pythonmodule $TESTSUITES
    fi
fi

# ==================== autoreport ====================

# public version
cd /tmp
dist=Tapper-autoreport
if [ ! -d $dist ] ; then git clone ${GITPREFIXTAPPERLIBS}/$dist ; fi
if [ -d $dist ] ; then
    cd $dist
    cp tapper-autoreport /opt/tapper/bin/
fi

# OSRC, may overwrite public versions
cd /tmp
dist=autoreport-testscripts
if [ ! -d $dist ] ; then git clone git://wotan/$dist ; fi
if [ -d $dist ] ; then
    cd $dist
    cp tapper-autoreport autoreport-utils /opt/tapper/bin/
fi

# ===========================================================

/tmp/tapper-starterkit/utils/create-symlinks
