#! /bin/bash

export TAPPER_SERVER
export TAPPERFROMGIT
export GITPREFIXTAPPERLIBS
export GITPREFIXTESTSUITES
export PYTHONSTATICTWEAKS
export PERLVERSION

export CPUCOUNT=`cat /proc/cpuinfo | grep vendor_id | wc -l`
export PERLVERSION=${PERLVERSION:-5.12.3}
export PERLBREW_ROOT=/opt/tapper/perl
export TWMC_TEST_PORT=9876
export PERL_AUTOINSTALL="--defaultdeps"
export TEST_JOBS=${CPUCOUNT}
export CPAN=/opt/tapper/perl/perls/current/bin/cpan
export PERL=/opt/tapper/perl/perls/current/bin/perl
. /opt/tapper/perl/etc/bashrc

TAPPERMODULES="$*"

# build from CPAN (which solves dependencies)
# and optionally from git on top
for module in $TAPPERMODULES ; do
        echo "" ; echo "" ; echo ""
        echo "***************** $module *******************"
        echo "" ; echo "" ; echo ""
    $CPAN $module || $CPAN -f $module
done
if [ "x1" == "x$TAPPERFROMGIT" ] ; then
    $CPAN Module::Install::AuthorRequires
    $CPAN Module::Install::WriteAll
    $CPAN Module::Install
    for module in $TAPPERMODULES ; do
        echo "" ; echo "" ; echo ""
        echo "***************** $module (from git) *******************"
        echo "" ; echo "" ; echo ""
        dist=$(echo $module | sed -e 's/::/-/g')
        cd /tmp/
        rm -fr $dist
        git clone ${GITPREFIXTAPPERLIBS}/$dist
        cd $dist
        DISTTRACKFILE=/tmp/tapper_last_gitrev_${dist}
        CURRENT_REV=$(git rev-parse HEAD)
        if [ -r $DISTTRACKFILE ] ; then
            LAST_REV=$(cat $DISTTRACKFILE)
        else
            LAST_REV=none
        fi

        if [ "x$CURRENT_REV" = "x$LAST_REV" ] ; then
            echo ""
            echo "*** $dist is up-to-date (last-rev: $LAST_REV; current-rev:$CURRENT_REV)"
            echo ""
            break
        fi

        # recursively resolve dependencies in git
        DEPENDENCIES=$(grep "requires.*'Tapper::" Makefile.PL | cut -d"'" -f2 | sort | uniq)
        DEPENDENCIES="$(echo $DEPENDENCIES)" # strip newlines
        echo "*** GIT TAPPER DEPENDENCIES: $DEPENDENCIES"
        for d in $DEPENDENCIES ; do
            if echo "$INSTALLEDTAPPERDEPS dummyHfill" | grep -q "\b${d}[^:]" ; then
                echo "    GIT TAPPER DEPENDENCY: $d already installed"
            else
                echo "    GIT TAPPER DEPENDENCY: $d"
                export INSTALLEDTAPPERDEPS="$d $INSTALLEDTAPPERDEPS"
                /tmp/tapper-starterkit/utils/prepare-perlmodule $d
            fi
        done

        echo "***************** continue $module (from git) *******************"
        if [ -e dist.ini ] ; then
             git clean -dxf
             $CPAN $(dzil listdeps | grep -v Tapper)
             dzil test && dzil run $CPAN -f .
        else
            $PERL Makefile.PL
            make
            make manifest
            DISTDIR=$(make distdir 2>&1 | grep 'rm -rf ' | cut -d" " -f3-)
            cd $DISTDIR
            $CPAN -f .
        fi
        echo $CURRENT_REV > $DISTTRACKFILE
    done
fi

/tmp/tapper-starterkit/utils/create-symlinks
