#! /bin/bash


# This is *very* specific to OSRC internal needs

export TAPPERFROMGIT
export GITPREFIXTAPPERLIBS
export GITPREFIXTESTSUITES
export PYTHONSTATICTWEAKS

export CPUCOUNT=`cat /proc/cpuinfo | grep vendor_id | wc -l`

TAPPERMODULES="$*"
PYTHONPREFIX=/opt/tapper/python


if [ "x1" == "x$TAPPERFROMGIT" ] ; then

    # git checkout
    cd /tmp/
    if [ ! -d OSRC-TestSuites ] ; then
        git clone git://wotan/OSRC-TestSuites
    fi

    # successfully cloned? Then we are probably in OSRC
    if [ -d OSRC-TestSuites ] ; then
        cd OSRC-TestSuites
        git pull
        for module in $TAPPERMODULES ; do
            cd /tmp/OSRC-TestSuites/python/$module
            echo "" ; echo "" ; echo ""
            echo "********************** $module (from git) **********************************"
            echo "                       (" `pwd` ")"
            echo "" ; echo "" ; echo ""
            rm -f dist/*.egg
            set -x
            ${PYTHONPREFIX}/bin/python setup.py bdist_egg
            ${PYTHONPREFIX}/bin/easy_install -Z dist/*.egg  # -Z to unpack egg file
            set +x
        done
    fi
fi

/tmp/tapper-starterkit/utils/create-symlinks
