#! /bin/sh
### BEGIN INIT INFO
# Provides:          tapper_cleanup 
# Required-Start:    $remote_fs $syslog $mysql
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Cleanup TapperDB on reboot"
NAME=true
DAEMON=/bin/$NAME
DAEMON_ARGS="--options args"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/tapper_cleanup

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
    if ps auxwww|grep -v grep|grep -q tapper-mcp-child ; then
        echo "MCP must not be running while cleanup."
        echo "Stop it first with"
        echo "   /etc/init.d/tapper_mcp_daemon stop"
        echo "and try again."
        exit 1
    fi
    echo "Freeing hosts"
    DSN=$(/opt/tapper/perl/perls/current/bin/perl -MTapper::Config -E 'print Tapper::Config->subconfig->{database}{TestrunDB}{dsn}')
    if echo $DSN | grep dbi:Pg ; then
        echo "update host set free=1;"                                                 | psql -U tapper -d testrundb
        echo "update testrun_scheduling set status='finished' where status='running';" | psql -U tapper -d testrundb
        echo "delete from state;"                                                      | psql -U tapper -d testrundb
        echo "delete from message;"                                                    | psql -U tapper -d testrundb
    else
        echo "update host set free=1;"                                                 | mysql -utapper -ptapper testrundb
        echo "update testrun_scheduling set status='finished' where status='running';" | mysql -utapper -ptapper testrundb
        echo "delete from state;"                                                      | mysql -utapper -ptapper testrundb
        echo "delete from message;"                                                    | mysql -utapper -ptapper testrundb
    fi
}

#
# Function that stops the daemon/service
#
do_stop()
{
	return 0
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
	return 0
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
       ;;
  #reload|force-reload)
	#
	# If do_reload() is not implemented then leave this commented out
	# and leave 'force-reload' as an alias for 'restart'.
	#
	#log_daemon_msg "Reloading $DESC" "$NAME"
	#do_reload
	#log_end_msg $?
	#;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
